name: Promote Terraform changes to production environment

on:
    workflow_dispatch:
        inputs:
            cloud_provider:
                description: 'Cloud provider for the environment'
                required: true
                type: choice
                options:
                    - aws
                    - azure
                    - gcp
            workspace:
                description: 'Terraform workspace to use'
                required: true
                type: choice
                options:
                    - platform_development
                    - innovation_development

permissions:
    contents: write
    pull-requests: write
            
jobs:
    terraform-plan-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.0
            

            - name: Configure AWS CLI
              if: ${{ github.event.inputs.cloud_provider == 'aws' }}
              run: |
                  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                  aws configure set default.region $AWS_DEFAULT_REGION
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Initialize Terraform
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/test/ init

            - name: Validate Terraform configuration
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/test/ validate
            
            - name: Plan Terraform changes
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/test/ plan

            - name: Output environment
              run: echo "Successfull terraform plan in test environment"
    deploy-to-test:
        runs-on: ubuntu-latest
        needs: terraform-plan-test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Git user
              run: |
                git config --global user.name ${{ github.actor }}
                git config --global user.email ${{ github.actor }}@users.noreply.github.com
            
            - name: Create deployment branch
              run: |
                git switch -c ${{ github.event.inputs.workspace }}-prod-deployment
                echo "Created branch for deployment to test environment"

            - name: Copy test to prod
              run: |


                  find terraform/${{ github.event.inputs.workspace }}/environment/${{ github.event.inputs.cloud_provider }}/test \
                    -maxdepth 1 \
                    -type f \
                    -name "*.tf" \
                    ! -name "environments.tf" \
                    ! -name "backends.tf" \
                    -exec cp -v {} terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/prod/ \;
                  echo "Copied test to prod environment"
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.0
            
            - name: Configure AWS CLI
              if: ${{ github.event.inputs.cloud_provider == 'aws' }}
              run: |
                  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                  aws configure set default.region $AWS_DEFAULT_REGION
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            
            - name: Initialize Terraform
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/prod/ init

            - name: Validate Terraform configuration
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider }}/prod/ validate

            - name: Plan Terraform changes
              run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider}}/prod/ plan

            - name: Commit & merge changes to main
              run: |
                  git add .
                  git commit -m "Deploying changes to production environment for ${{ github.event.inputs.workspace }} on ${{ github.event.inputs.cloud_provider }}"
                  git push origin ${{ github.event.inputs.workspace }}-prod-deployment
                  git switch main
                  git merge --no-ff ${{ github.event.inputs.workspace }}-prod-deployment

            ### Uncomment the following lines to apply the Terraform changes automatically
            # - name: Apply Terraform changes
            #   run: terraform -chdir=terraform/${{github.event.inputs.workspace}}/environment/${{ github.event.inputs.cloud_provider}}/prod/ apply -auto-approve